version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  appserver:
    networks:
      splunknet:
        aliases:
          - appserver
    image: nwang92/nginx-mitm
    hostname: appserver
    container_name: appserver
    ports:
      - 80
    volumes:
      - ../tests/fixtures:/www/data

  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    container_name: so1
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD
      - SPLUNK_APPS_URL=http://appserver/splunk_app_example.tgz
      - DEBUG=true
    ports:
      - 8000
      - 8089
